# Generated by scripts/release.sh — edit that, not this.
cask "cpx-app" do
  version "0.2.2"
  sha256 "1946953807b083a2e97ed163f3fc11434a7dd5fa47d3873d9f3b7dc6d669f5a6"

  url "https://github.com/menico/cpx/releases/download/v#{version}/cpx-#{version}-universal.dmg"
  name "cpx"
  desc "Menu-bar app for Claude Code and Codex profiles, with usage and spend"
  homepage "https://github.com/menico/cpx"

  app "cpx.app"

  # The app is ad-hoc signed rather than notarised, so macOS quarantines it
  # on download. Removing the flag here saves a right-click-open.
  postflight do
    system_command "/usr/bin/xattr",
                   args: ["-dr", "com.apple.quarantine", "#{appdir}/cpx.app"],
                   sudo: false
  end

  # Deliberately does not list ~/.claude-profiles. Profiles hold real state
  # — session history for anything in  mode, and adopted directories are
  # the user's own working directories. Uninstalling the app must not take
  # them;  can remove a profile deliberately.
  zap trash: [
    "~/Library/Application Support/io.github.menico.cpx",
  ]
end
