# Generated by scripts/release.sh — edit that, not this.
cask "cpx" do
  version "0.1.0"
  sha256 "56ade583d76fd5474ff7f8a60f113e24a88f2a95a4fc25d513814dbb58b298b2"

  url "https://github.com/menico/cpx/releases/download/v#{version}/cpx-#{version}-universal.dmg"
  name "cpx"
  desc "Menu-bar app for managing Claude Code profiles"
  homepage "https://github.com/menico/cpx"

  app "cpx.app"

  # The app is ad-hoc signed rather than notarised, so macOS quarantines it
  # on download. Removing the flag here saves a right-click-open.
  postflight do
    system_command "/usr/bin/xattr",
                   args: ["-dr", "com.apple.quarantine", "#{appdir}/cpx.app"],
                   sudo: false
  end

  # Deliberately does not list ~/.claude-profiles. Profiles hold real state
  # — session history for anything in `own` mode, and adopted directories are
  # the user's own working directories. Uninstalling the app must not take
  # them; `cpx` can remove a profile deliberately.
  zap trash: [
    "~/Library/Application Support/io.github.menico.cpx",
  ]
end
