# Generated by scripts/release.sh — edit that, not this.
class Cpx < Formula
  desc "Run several Claude Code and Codex accounts side by side"
  homepage "https://github.com/menico/cpx"
  version "0.2.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/menico/cpx/releases/download/v0.2.0/cpx-0.2.0-aarch64-apple-darwin.tar.gz"
      sha256 "237f449c7a7c458b2be97afdd7085096dc63ac09ccd0f5d367ff48495f1281ca"
    end
    on_intel do
      url "https://github.com/menico/cpx/releases/download/v0.2.0/cpx-0.2.0-x86_64-apple-darwin.tar.gz"
      sha256 "e2b2da54c03a63ce19a7a80dc0d808db43af95ae1d47e82188231cb1edbfec7f"
    end
  end

  def install
    bin.install "cpx"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/cpx --version")
  end
end
