# Generated by scripts/release.sh — edit that, not this.
class Cpx < Formula
  desc "Run several Claude Code accounts side by side"
  homepage "https://github.com/menico/cpx"
  version "0.1.3"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/menico/cpx/releases/download/v0.1.3/cpx-0.1.3-aarch64-apple-darwin.tar.gz"
      sha256 "f9fdd3314a2c1266b20f9e3a8c6bd98361e9dff77f13f267cda8d49ae9d32ffd"
    end
    on_intel do
      url "https://github.com/menico/cpx/releases/download/v0.1.3/cpx-0.1.3-x86_64-apple-darwin.tar.gz"
      sha256 "1d57ce10002be86e40f610c553a9f2bcfa9015ac44b384367bbfa7e9e8664cbd"
    end
  end

  def install
    bin.install "cpx"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/cpx --version")
  end
end
