# Generated by scripts/release.sh — edit that, not this.
class Cpx < Formula
  desc "Run several Claude Code accounts side by side"
  homepage "https://github.com/menico/cpx"
  version "0.1.6"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/menico/cpx/releases/download/v0.1.6/cpx-0.1.6-aarch64-apple-darwin.tar.gz"
      sha256 "e0333488f491216848bcba80733d9248bbc5153ac9b9a4e6a4e272d3633834ae"
    end
    on_intel do
      url "https://github.com/menico/cpx/releases/download/v0.1.6/cpx-0.1.6-x86_64-apple-darwin.tar.gz"
      sha256 "910b93068a788f2816403a2a6167a3c78825eabbcb1df0ac9328c18fbe44159d"
    end
  end

  def install
    bin.install "cpx"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/cpx --version")
  end
end
